### ISSUE TITLE
How to use this library 

### ISSUE THREAD

**Issue by zeeshan-algo** [benjgrad/grapesjs-plugin-scroll#1]
HI @benjgrad How to use this library . I have created a component and i want to show animations on scroll how can i achieve this .   Like what would i have to write in the component?

**Comment by benjgrad** [comment]
Hi @zeeshan-algo, you just need to specify the classnames mentioned in the readme, and shown in the demo site. The classnames are added as the user scrolls past the threshold. If you want a specific transition, add the transition to that class.
